# Generated by Django 6.0 on 2025-12-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='used_by',
            field=models.ManyToManyField(blank=True, to='delivery.user'),
        ),
    ]
