# Generated by Django 6.0 on 2025-12-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('CANCELLED', 'Cancelled'), ('DELIVERED', 'Delivered')], default='PLACED', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
