# Generated by Django 6.0 on 2026-01-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_restaurant_picture_alter_restaurant_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='picture',
            new_name='picture_url',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='picture_file',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
