# Generated by Django 6.0 on 2026-01-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_rename_picture_restaurant_picture_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='picture_url',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(max_length=255),
        ),
    ]
