# Generated by Django 6.0 on 2026-01-06 14:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_rename_picture_url_restaurant_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='picture_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='restaurant_image'),
        ),
    ]
