# Generated by Django 6.0 on 2026-01-06 14:51

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_alter_restaurant_picture_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='item_image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurant'),
        ),
    ]
