# Generated by Django 6.0 on 2026-01-06 15:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_alter_item_description_alter_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='menu_image'),
        ),
    ]
