# Generated by Django 6.0 on 2026-01-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_alter_item_picture_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
