# Generated by Django 6.0 on 2026-01-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_order_rating_order_review_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='', editable=False, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
