# Generated by Django 6.0 on 2026-01-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='order',
            name='review',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, editable=False, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
