# Generated by Django 6.0 on 2026-01-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_remove_order_rating_remove_order_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
    ]
