# Generated by Django 6.0 on 2026-01-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0023_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='coupon_discount',
            field=models.FloatField(default=0),
        ),
    ]
