# Generated by Django 6.0 on 2026-01-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0024_orderitem_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.FloatField(default=0),
        ),
    ]
