# Generated by Django 6.0 on 2026-01-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0025_order_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
