# Generated by Django 6.0 on 2026-01-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0029_userextraaddress_userextramobile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextraaddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userextramobile',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userextramobile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
