# Generated by Django 6.0 on 2026-01-17 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0031_order_delivery_address_order_delivery_address_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
